# トップ
index:
    path: /
    controller: App\Controller\OneDayOneSceneController::index

input_name:
  path: /input_name
  controller: App\Controller\OneDayOneSceneController::inputName

choose_decks:
  path: /choose_decks
  controller: App\Controller\OneDayOneSceneController::chooseDecks

check_deck_and_name:
  path: /check_deck_and_name
  controller: App\Controller\OneDayOneSceneController::checkDeckAndName

question:
  path: /question
  controller: App\Controller\OneDayOneSceneController::question

result:
  path: /result
  controller: App\Controller\OneDayOneSceneController::result

chooseScene:
  path: /chooseScene
  controller: App\Controller\OneDayOneSceneController::chooseScene

checkBeforePerformance:
  path: /checkBeforePerformance
  controller: App\Controller\OneDayOneSceneController::checkBeforePerformance

countdown:
  path: /countdown
  controller: App\Controller\OneDayOneSceneController::countdown

performance:
  path: /performance
  controller: App\Controller\OneDayOneSceneController::performance

# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
